apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location / {
          proxy_pass http://studentportfolio;
        }

        location /api/ {
          proxy_pass http://backend:5000/;
        }

        location /transactions/ {
          proxy_pass http://transactions:3000/;
        }
      }
    }